name: material_theme_builder
description: Simple Flutter interface for the Material Theme Builder.
version: 1.0.0
homepage: https://github.com/nathanielxd/material-theme-builder

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities: ^0.1.4

dev_dependencies:
  flutter_lints: ^2.0.0