name: material_theme_builder
description: Simple Flutter interface for the Material Theme Builder.
version: 1.0.4
homepage: https://github.com/nathanielxd/material-theme-builder

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.7"

dependencies:
  flutter:
    sdk: flutter
  material_color_utilities:

dev_dependencies:
  flutter_lints: ^2.0.0